import { chromium } from "playwright";
const browser = await chromium.launch({ channel: "chrome" });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await page.goto("https://luma-english-ten.vercel.app", { waitUntil: "networkidle", timeout: 60000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: ".assets/luma-hero.png" });
await page.evaluate(() => window.scrollTo(0, 1400));
await page.waitForTimeout(600);
await page.screenshot({ path: ".assets/luma-section.png" });
console.log("captured", await page.title());
await browser.close();
