import { writeFile } from "node:fs/promises";

/**
 * Hero ASCII sculpture, pre-computed at build time and emitted as a TS constant so the
 * runtime cost is a single <pre> and nothing else. Same metaball field + gradient
 * lighting as the Figma source, rendered at two densities.
 */
function sculpture(COLS, ROWS) {
  const RAMP = "@%#*+=~-:.·", ASPECT = 0.55;
  const blobs = [
    { x: 0.30, y: 0.46, r: 0.26, w: 1.0 }, { x: 0.45, y: 0.34, r: 0.17, w: 0.72 },
    { x: 0.40, y: 0.64, r: 0.19, w: 0.66 }, { x: 0.58, y: 0.52, r: 0.15, w: 0.52 },
    { x: 0.66, y: 0.38, r: 0.10, w: 0.30 }, { x: 0.20, y: 0.62, r: 0.11, w: 0.34 },
  ];
  const field = (u, v) => {
    let d = 0;
    for (const b of blobs) {
      const dx = u - b.x, dy = (v - b.y) * ASPECT;
      d += b.w * Math.exp(-(dx * dx + dy * dy) / (2 * b.r * b.r * 0.3));
    }
    return d;
  };
  const hash = (i, j) => ((Math.sin(i * 12.9898 + j * 78.233) * 43758.5453) % 1 + 1) % 1;
  const EPS = 0.004, L = { x: -0.62, y: -0.7, z: 0.35 }, LN = Math.hypot(L.x, L.y, L.z);
  const lines = [];
  for (let j = 0; j < ROWS; j++) {
    let line = "";
    for (let i = 0; i < COLS; i++) {
      const u = i / COLS, v = j / ROWS, f = field(u, v);
      const gx = (field(u + EPS, v) - field(u - EPS, v)) / (2 * EPS);
      const gy = (field(u, v + EPS) - field(u, v - EPS)) / (2 * EPS);
      const nz = 1.6, nl = Math.hypot(gx, gy, nz) || 1;
      const lam = ((-gx * L.x - gy * L.y + nz * L.z) / (nl * LN) + 1) / 2;
      const edge = 0.3 + 0.05 * Math.sin(u * 9 + v * 6);
      let body = (f - edge) / 0.55;
      body -= 0.55 * Math.pow(Math.max(0, u - 0.55), 1.4) * 2.4;
      body -= 0.4 * Math.pow(Math.max(0, v - 0.55), 1.6) * 1.9;
      body = Math.max(0, Math.min(1, body));
      const scan = j === Math.round(ROWS * 0.45) || j === Math.round(ROWS * 0.45) + 1 ? 0.14 : 0;
      let t = body * (0.34 + 0.78 * lam) + scan + 0.045 * Math.sin(u * 30 + v * 11) + (hash(i, j) - 0.5) * 0.1;
      t = Math.max(0, Math.min(1, t));
      if (body <= 0.001) {
        const res = Math.max(0, f - 0.12) * 1.8 + 0.04;
        line += hash(i * 3, j * 7) < res ? (hash(i, j) < 0.5 ? "·" : ".") : " ";
        continue;
      }
      line += RAMP[Math.max(0, Math.min(RAMP.length - 1, Math.round((1 - t) * (RAMP.length - 1))))];
    }
    lines.push(line.replace(/\s+$/, ""));
  }
  return lines.join("\n");
}

const desktop = sculpture(148, 62);
const mobile = sculpture(74, 22);
const out = `// GENERATED by scripts/gen-ascii.mjs — do not edit by hand.
// Metaball field lit by its own gradient: reads as volume at distance, as characters up close.

export const asciiSculpture = ${JSON.stringify(desktop)};

export const asciiSculptureCompact = ${JSON.stringify(mobile)};
`;
await writeFile("src/content/ascii.ts", out);
console.log("desktop", desktop.length, "chars ·", desktop.split("\\n").length, "lines");
console.log("mobile", mobile.length, "chars");
