import { chromium } from "playwright";
const BASE = "http://localhost:3112/work/lead-radar";
const browser = await chromium.launch({ channel: "chrome" });
const desk = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await desk.goto(BASE, { waitUntil: "networkidle" });
await desk.addStyleTag({ content: "html{scroll-behavior:auto!important}" });
const y = await desk.$eval("#band-06", (el) => el.getBoundingClientRect().top + window.scrollY);
await desk.evaluate((v) => window.scrollTo(0, v - 240), y);
await desk.waitForTimeout(1200);
await desk.screenshot({ path: ".screens/case-lead-result.png" });
await desk.screenshot({ path: ".screens/case-lead-full.png", fullPage: true });
console.log("desktop overflowX:", await desk.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
const bands = await desk.$$eval("section[aria-labelledby^='band-'] h2", (els) => els.map((e) => e.textContent));
console.log("bands:", JSON.stringify(bands));
const mob = await browser.newPage({ viewport: { width: 390, height: 844 } });
await mob.goto(BASE, { waitUntil: "networkidle" });
const my = await mob.$eval("#band-06", (el) => el.getBoundingClientRect().top + window.scrollY);
await mob.evaluate((v) => window.scrollTo(0, v - 120), my);
await mob.waitForTimeout(1000);
await mob.screenshot({ path: ".screens/mobile-case-result.png" });
console.log("mobile overflowX:", await mob.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await browser.close();
